# Site settings
title: G. BERGERET
description: Geoffrey Bergeret, Freelance Cloud/DevOps/Infrastructure/Network Engineer
# baseurl: "" # the subpath of your site, e.g. /blog
url: "https://www.gbergeret.com"

# User settings
author:
  title: Cloud/DevOps/Infrastructure Engineer
  name: Geoffrey Bergeret
  expertise: >
    With my experience in Infrastructure, Networking, Security, and Cloud, I can
    help and advise you on your digital projects. I also have a strong
    understanding in end-user product and lean development which helps a lot when
    working in start up environments.

    I started to work as a consultant to share my experience and help smaller
    businesses improve their Cloud Infrastructure until they are ready to grow
    their team.
  email: contact@gbergeret.com
  phone: +44 7871 334653
  website: https://www.gbergeret.org
  # skype: geoffrey.bergeret
  linkedin: gbergere
  github: gbergeret
  twitter: gbergere
  # facebook: changeme


# Google-analytics
google-analytics:
  id: ""

exclude: ['package.json', 'src', 'node_modules']
